name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Vérification de la présence de SSH_PRIVATE_KEY
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "❌ SECRET SSH_PRIVATE_KEY NON DÉTECTÉ !"
            exit 1
          else
            echo "✅ SECRET SSH_PRIVATE_KEY détecté"
          fi

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 51.75.124.6
          username: debian
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/benoit-demonchaux-website
            git pull origin main
            sudo systemctl restart nginx
